name: WordPress Coding Standards Check (Modified Lines)
on:
  pull_request:
    branches:
      - dev # Change this to your dev branch
jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer

      - name: Install Composer dependencies
        run: composer install

      - name: Get modified PHP files
        id: changed-files
        run: |
          git diff --name-only HEAD^..HEAD | grep '\.php$' > changed-files.txt
          echo "Modified PHP files:"
          cat changed-files.txt

      - name: Check WordPress Coding Standards
        run: |
          while IFS= read -r file; do
            vendor/bin/phpcs --standard=WordPress-Core $file
          done < changed-files.txt

