name: WordPress Coding Standards Check (Modified Lines)
on:
  pull_request:
    branches:
      - dev # Change this to your dev branch
jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer, phpcs

      - name: Install Composer dependencies
        run: composer install

      - name: Fetch All Branches
        run: git fetch --all --prune
          
      - name: Get modified PHP files
        id: changed-files
        run: |
          git diff --name-only --diff-filter=ACMRTUXB origin/dev...origin/${{ github.head_ref }} | grep \\.php$ > changed-files.txt
          echo "Modified PHP files:"
          cat changed-files.txt

      - name: Check WordPress Coding Standards
        run: phpcs --standard=WordPress-Core MyClass.php index.php

