name: WordPress CS check
on: pull_request
jobs:
  phpcs:
    name: WPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: WPCS check
        uses: 10up/wpcs-action@stable
        with:
          repo_branch: 'dev' # Branch name
          paths: '.' # Paths to check, space separated
          excludes: '' # Paths to excludes, space separated
          standard: 'WordPress' # CS name
          enable_warnings: 'false' # Enable checking for warnings (-w)
          extra_args: '-d error_reporting="E_ALL&~E_DEPRECATED"'
